// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/auth/error" | "/auth/signin" | "/auth/verify-request" | "/catalog" | "/catalog/[id]" | "/catalog/new" | "/clients" | "/clients/[id]" | "/clients/new" | "/editor" | "/p/[token]" | "/settings" | "/settings/profile"
type AppRouteHandlerRoutes = "/api/auth/[...nextauth]" | "/api/clients" | "/api/clients/[id]" | "/api/pdf" | "/api/products" | "/api/proposal-templates" | "/api/proposals" | "/api/proposals/[id]" | "/api/proposals/[id]/duplicate" | "/api/proposals/[id]/share" | "/api/track" | "/api/upload" | "/api/workspace/settings" | "/api/workspace/upload" | "/p/[token]/pdf"
type PageRoutes = never
type LayoutRoutes = "/" | "/editor"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/clients": {}
  "/api/clients/[id]": { "id": string; }
  "/api/pdf": {}
  "/api/products": {}
  "/api/proposal-templates": {}
  "/api/proposals": {}
  "/api/proposals/[id]": { "id": string; }
  "/api/proposals/[id]/duplicate": { "id": string; }
  "/api/proposals/[id]/share": { "id": string; }
  "/api/track": {}
  "/api/upload": {}
  "/api/workspace/settings": {}
  "/api/workspace/upload": {}
  "/auth/error": {}
  "/auth/signin": {}
  "/auth/verify-request": {}
  "/catalog": {}
  "/catalog/[id]": { "id": string; }
  "/catalog/new": {}
  "/clients": {}
  "/clients/[id]": { "id": string; }
  "/clients/new": {}
  "/editor": {}
  "/p/[token]": { "token": string; }
  "/p/[token]/pdf": { "token": string; }
  "/settings": {}
  "/settings/profile": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/editor": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
