// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(dashboard)/catalog/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/catalog/[id]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/catalog/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/catalog/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/catalog/new">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/catalog/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/catalog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/catalog">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/catalog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/clients/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clients/[id]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/clients/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/clients/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clients/new">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/clients/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clients">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/settings/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/profile">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/settings/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/error/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/error">> = Specific
  const handler = {} as typeof import("../../app/auth/error/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/signin">> = Specific
  const handler = {} as typeof import("../../app/auth/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/verify-request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/verify-request">> = Specific
  const handler = {} as typeof import("../../app/auth/verify-request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/editor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/editor">> = Specific
  const handler = {} as typeof import("../../app/editor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/p/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/p/[token]">> = Specific
  const handler = {} as typeof import("../../app/p/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clients/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clients/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/clients/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clients/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clients">> = Specific
  const handler = {} as typeof import("../../app/api/clients/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pdf">> = Specific
  const handler = {} as typeof import("../../app/api/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products">> = Specific
  const handler = {} as typeof import("../../app/api/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/proposal-templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proposal-templates">> = Specific
  const handler = {} as typeof import("../../app/api/proposal-templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/proposals/[id]/duplicate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proposals/[id]/duplicate">> = Specific
  const handler = {} as typeof import("../../app/api/proposals/[id]/duplicate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/proposals/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proposals/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/proposals/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/proposals/[id]/share/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proposals/[id]/share">> = Specific
  const handler = {} as typeof import("../../app/api/proposals/[id]/share/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/proposals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proposals">> = Specific
  const handler = {} as typeof import("../../app/api/proposals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/track/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/track">> = Specific
  const handler = {} as typeof import("../../app/api/track/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/workspace/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspace/settings">> = Specific
  const handler = {} as typeof import("../../app/api/workspace/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/workspace/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspace/upload">> = Specific
  const handler = {} as typeof import("../../app/api/workspace/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/p/[token]/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/p/[token]/pdf">> = Specific
  const handler = {} as typeof import("../../app/p/[token]/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/editor/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/editor">> = Specific
  const handler = {} as typeof import("../../app/editor/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
